import "./globals.css";

import {
  montserrat,
  nunitoSans,
  libreBaskerville,
} from "@/lib/fonts";

import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";
import PageWrapper from "@/components/common/PageWrapper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`
        ${montserrat.variable}
        ${nunitoSans.variable}
        ${libreBaskerville.variable}
        h-full antialiased
      `}
    >
      <body className="min-h-full flex flex-col bg-[#EAE8E2]">
        <Header />

        <PageWrapper>
          {children}
        </PageWrapper>

        <Footer />
      </body>
    </html>
  );
}